package com.fse3.auction.common.dto;

public enum CategoryType {
    ANIMAL_PET_SUPPLIES, APPAREL_AND_ACCESSORIES, ARTS_AND_ENTERTAINMENT, BABY_PRODUCTS, BUSINESS_INDUSTRIAL, CAMERAS, ELECTRONICS,
    FURNITURE, HARDWARE, HEALTH_AND_BEAUTY, DECOR, GARDENING, HOME, KITCHEN, LUGGAGE, MEDIA, OFFICE_SUPPLIES, SPORTING_GOODS
}
