package com.fse3.auction.common.dto;

public enum CategoryType {
    ANIMAL_PET_SUPPLIES,//0
    APPAREL_AND_ACCESSORIES,//1
    ARTS_AND_ENTERTAINMENT,//2
    BABY_PRODUCTS,//3
    BUSINESS_INDUSTRIAL,//4
    CAMERAS,//5
    ELECTRONICS, //6
    FURNITURE, //7
    HARDWARE,//8
    HEALTH_AND_BEAUTY,//9
    DECOR,//10
    GARDENING,//11
    HOME,//12
    KITCHEN,//13
    LUGGAGE,//14
    MEDIA,//15
    OFFICE_SUPPLIES,//16
    SPORTING_GOODS//17
}
